version: '3'
services:
  task_manager_api:
    container_name: task_manager_api
    ports:
      - "8000:8000"
    image: ghcr.io/caalek/task-manager-api:latest
    volumes:
      - ./database:/app/database
    restart: unless-stopped