name: build and push image
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      name: Check out code

    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: task-manager-api
        tags: latest
        registry: ghcr.io
        dockerfile: Dockerfile
        multiPlatform: true
        platform: linux/amd64,linux/arm64
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}